GRANT USAGE ON *.* TO `usuarioPlannerJournal`@`localhost` IDENTIFIED BY PASSWORD '*';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `plannerjournal`.* TO `usuarioPlannerJournal`@`localhost` WITH GRANT OPTION;